location = /platform/finance {
    return 302 /platform/finance/;
}

location ^~ /platform/finance/ {
    client_max_body_size 100m;
    proxy_pass http://127.0.0.1:3180/;
    include snippets/aqllm-3.0-proxy.conf;
}
